Update de.json
WilliamVenner/gmpublisher pull request #84
Opened 2022-05-22 11:45 UTC by SupreemeGuy

2022-06-27 12:26 UTC, WilliamVenner commented
Some of the translation strings have been removed or reverted to English in your changes

2022-08-26 23:58 UTC, SupreemeGuy commented
Updated now

2024-01-21 18:05 UTC, Luiggi33 requested changes

2024-01-21 18:05 UTC, Luiggi33 commented on i18n/de.json
>  		"image": "Image",
```suggestion
		"image": "Bild",
```

2024-01-21 18:05 UTC, Luiggi33 commented on i18n/de.json
>  		"unknown": "Unknown ({extension})"
```suggestion
		"unknown": "Unbekannt ({extension})"
```

2024-02-06 00:52 UTC, WilliamVenner commented
@SupreemeGuy Please can you address Luiggi33's suggestions? Cheers :D

2024-02-06 08:42 UTC, SupreemeGuy commented on i18n/de.json
> +	"github_star": "Mit einem Stern auf GitHub bewerten",
Würde schon sagen, dass Sterne auf GitHub als Bewertung funktionieren. Ist so ähnlich wie bei YouTube mit den Likes. Schau dir mal https://docs.github.com/en/get-started/exploring-projects-on-github/saving-repositories-with-stars an :)

2024-02-06 09:03 UTC, Luiggi33 commented on i18n/de.json
> +	"github_star": "Mit einem Stern auf GitHub bewerten",
They literally talk about saving your favorite repos, not rating them. It's like saying youtubes playlist feature is not to save, categorise and even promote certained content, but to rate it.

2024-02-06 09:20 UTC, Luiggi33 approved these changes

2024-02-06 15:02 UTC, merged